# Generated by Django 4.2.6 on 2025-03-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_members',
            new_name='Staff_member',
        ),
    ]
