# Generated by Django 4.2.6 on 2025-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_members', '0002_rename_staff_members_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff_member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
