# Generated by Django 4.2.6 on 2025-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_members', '0003_staff_member_joined_date_staff_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_member',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
